FROM gradle:jdk11 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build --no-daemon

FROM openjdk:11-jre-slim
EXPOSE 8081
RUN mkdir /app
#
COPY api-test-0.0.1-SNAPSHOT.jar api-test-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=$(enviroment)", "-jar", "api-test-0.0.1-SNAPSHOT.jar"]