FROM gradle:jdk11 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build --no-daemon

FROM openjdk:11-jre-slim
EXPOSE 8080
RUN mkdir /app
#
COPY --from=build /home/gradle/src/build/libs/api-test-0.0.1-SNAPSHOT.jar api-test-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=dev", "-jar", "api-test-0.0.1-SNAPSHOT.jar"]