apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-java-app
 # namespace: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
      - name: java-app
        image: 050264659180.dkr.ecr.us-east-1.amazonaws.com/cuscatlan-java:1402
        resources:
          requests:
            cpu: 300m
            memory: 500Mi
          limits:
            cpu: 900m
            memory: 800Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-java-app
  #namespace: development

spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: java-app