apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-jenkins
 # namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
          limits:
            cpu: 900m
            memory: 2048Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: svc-jenkins
  #namespace: development
 
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: LoadBalancer
  selector:
    app: jenkins