apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-nginx
  #namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 200m
            memory: 400Mi
          limits:
            cpu: 900m
            memory: 800Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  #namespace: development
  #annotations:
   # service.beta.kubernetes.io/role/elb: shared
   # kubernetes.io/cluster/EKS-Cuscatlan-dev: shared
   # service.beta.kubernetes.io/aws-load-balancer-type: external
   # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
   # service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: nginx