apiVersion: v1
kind: Service
metadata:
  name: svc-node-app
  #namespace: development
  #annotations:
  #  service.beta.kubernetes.io/azure-load-balancer-internal: "true"

spec:
  type: LoadBalancer
  #loadBalancerIP: 192.168.33.72 
  ports:
  - port: 80 
  selector:
    app: nodeapp