apiVersion: apps/v1
kind: Deployment
metadata:
  name: d-sonarqube
 # namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube
        resources:
          requests:
            cpu: 500m
            memory: 1024Mi
          limits:
            cpu: 900m
            memory: 2048Mi
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-sonarqube
  #namespace: development

spec:
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  type: LoadBalancer
  selector:
    app: sonarqube